### Setup

In [1]:
import numpy as np
import time

# Vectors

## Vector Creation

In [8]:
a = np.zeros(4); print(a, a.shape, a.dtype)
a = np.zeros((4,)); print(a, a.shape, a.dtype)
a = np.random.random_sample(4); print(a, a.shape, a.dtype)

[0. 0. 0. 0.] (4,) float64
[0. 0. 0. 0.] (4,) float64
[0.00260217 0.79201246 0.66128472 0.84435069] (4,) float64


In [13]:
a = np.arange(4.); print(a, a.shape, a.dtype)
a = np.random.rand(4); print(a, a.shape, a.dtype)

[0. 1. 2. 3.] (4,) float64
[0.97847388 0.04098577 0.52449813 0.12651425] (4,) float64


In [14]:
a = np.array([5,4,3,2]); print(a, a.shape, a.dtype)
a = np.array([5.,4,3,2]); print(a, a.shape, a.dtype)

[5 4 3 2] (4,) int64
[5. 4. 3. 2.] (4,) float64


## Operations on Vectors

### Indexing

In [18]:
# Vector indexing on one-dimensional vectors
a = np.arange(10); print(a)

# Access an element
print(a[2], a[2].shape, a[2].dtype) # Accessing the 3rd element

# Access the last element
print(a[-1], a[-1].shape, a[-1].dtype)

# If index isn't in range of the vector
try:
    c = a[10]

except Exception as e:
    print("The error message will be:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
2 () int64
9 () int64
The error message will be:
index 10 is out of bounds for axis 0 with size 10


### Slicing

In [21]:
a = np.arange(10); print(a)

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

[0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


### Single Vector Operations

In [23]:
a = np.array([1,2,3,4]); print(a)
b = -a; print(b) # Negates all elements of a
b = np.sum(a); print(b) # Sum all elements of a
b = np.mean(a); print(b) # Self explanatory
b = a**2; print(b) # Squares all elements of a

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]
